In [1]:
import numpy as np

In [3]:
matrix = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [5]:
matrix.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
m1=np.array([[1,2], [3,4]])
m2=np.array([[5,6], [7,8]])

In [8]:
m1

array([[1, 2],
       [3, 4]])

In [9]:
m2

array([[5, 6],
       [7, 8]])

In [10]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [11]:
m1.dot(m2)

array([[19, 22],
       [43, 50]])

In [14]:
np.linalg.det(m1)

-2.0000000000000004

In [15]:
np.linalg.det(m2)

-1.999999999999999

In [16]:
np.linalg.inv(m1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
np.linalg.eig(m1)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))