In [1]:
import numpy as np

In [2]:
l1=np.array([1,2,3])

In [3]:
l1

array([1, 2, 3])

In [4]:
type(l1)

numpy.ndarray

In [5]:
l=[1,2,3,4,5]

In [6]:
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
l1.dtype

dtype('int64')

In [8]:
l2 = np.array([1, 'text', dict()])

In [9]:
l2

array([1, 'text', {}], dtype=object)

In [10]:
l3=np.array([4,5,6], dtype='float')

In [11]:
l3

array([4., 5., 6.])

In [12]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [13]:
l1+l3

array([5., 7., 9.])

In [14]:
l1-l3

array([-3., -3., -3.])

In [15]:
l1/l3

array([0.25, 0.4 , 0.5 ])

In [16]:
l1[0
]

1

In [17]:
l1[-1]

3