In [23]:
import numpy as np

### метод 1

In [2]:
A=np.array([[5,3,2], [2,4,6], [2,9,1]])
b = np.array([1,8,3])

In [3]:
A

array([[5, 3, 2],
       [2, 4, 6],
       [2, 9, 1]])

In [4]:
b

array([1, 8, 3])

In [5]:
A_inv=np.linalg.inv(A)
A_inv

array([[ 0.25 , -0.075, -0.05 ],
       [-0.05 , -0.005,  0.13 ],
       [-0.05 ,  0.195, -0.07 ]])

In [6]:
A_inv.dot(b)

array([-0.5,  0.3,  1.3])

### метод2 - определители

In [7]:
a=np.linalg.det(A)

In [8]:
a

-199.99999999999991

In [9]:
A1=A.copy()

In [10]:
A1[:, 0]= b
A1

array([[1, 3, 2],
       [8, 4, 6],
       [3, 9, 1]])

In [11]:
a1=np.linalg.det(A1)
a1

99.99999999999996

In [12]:
round(a1/a, 1)

-0.5

In [13]:
A2=A.copy()
A2[:, 1]= b
A2

array([[5, 1, 2],
       [2, 8, 6],
       [2, 3, 1]])

In [14]:
a2=np.linalg.det(A2)
a2

-59.999999999999986

In [15]:
round(a2/a, 1)

0.3

In [19]:
A3=A.copy()
A3[:, 2]= b
A3

array([[5, 3, 1],
       [2, 4, 8],
       [2, 9, 3]])

In [20]:
a3=np.linalg.det(A3)
a3

-259.99999999999994

In [21]:
round(a3/a, 1)

1.3

### метод 3

In [22]:
np.linalg.solve(A, b)

array([-0.5,  0.3,  1.3])