In [1]:
import numpy as np

In [3]:
matrix = np.array([[1,2,3], [4,5,6]])

In [4]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix[0, 1]

2

In [6]:
matrix2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
matrix2[1:, :-1]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [9]:
matrix3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [10]:
matrix2+matrix3

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [11]:
test=np.array([1,2,3,4])

In [12]:
test+matrix3

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [13]:
test=np.arrray([1,2,3])

AttributeError: module 'numpy' has no attribute 'arrray'