In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
matrix=np.array([[1,2,3], [5,6,7]])

In [6]:
matrix

array([[1, 2, 3],
       [5, 6, 7]])

### shape

In [7]:
arr.shape

(4,)

In [8]:
matrix.shape

(2, 3)

### size

In [10]:
arr.size

4

In [11]:
matrix.size

6

### ndim

In [13]:
arr.ndim

1

In [14]:
matrix.ndim

2

### zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [21]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### identity

In [23]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### arange

In [24]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### linspace

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### aggregation

In [26]:
arr

array([1, 2, 3, 4])

In [27]:
arr.max()

4

In [28]:
arr.min()

1

In [30]:
arr.sum()

10

In [31]:
arr.prod()

24

In [32]:
arr.mean()

2.5

In [33]:
matrix.mean()

4.0

In [34]:
matrix.max()

7